const projects = [
    {
        id: 1,
        type: "website",
        title: "Bőrdíszműves weboldal",
        technolgies: "HTML-CSS-JavaScript",
        cardDescription: "Minta Béla bőrdíszműves portfólió weboldala.",
        popupDescription: "Minta Béla bőrdíszműves portfólió weboldala.",
        listItem1: "<li>HTML</li>",
        listItem2: "<li>CSS</li>",
        listItem3: "<li>JavaScript</li>",
        listItem4: "",
        listItem5: "",
        listItem6: "",
        imageSrc: "./assets/img/projects_img/leadherShop.png",
        imageAlt: "Bőrdíszműves projekt kép",
        githubLink:"https://github.com/",
        githubPagesLink: "https://github.com/",
    },
    {
        id: 2,
        type: "website",
        title: "Gipsz Jakab portfólió oldala",
        technolgies: "HTML-CSS-JavaScript",
        cardDescription: "Gipsz Jakab frontend webfejlesztő portfólió weboldala",
        popupDescription: "Gipsz Jakab frontend webfejlesztő portfólió weboldala",
        listItem1: "<li>HTML</li>",
        listItem2: "<li>CSS</li>",
        listItem3: "<li>JavaScript</li>",
        listItem4: "",
        listItem5: "",
        listItem6: "",
        imageSrc: "../assets/img/projects_img/gipsz.png",
        imageAlt: "Bőrdíszműves projekt kép",
        githubLink:"https://github.com/",
        githubPagesLink: "https://github.com/",
    },
    {
        id: 3,
        type: "app",
        title: "Példa projekt 3",
        technolgies: "HTML-CSS-JavaScript",
        cardDescription: "Ez a projekt kártyák megjelínítésének a mintája.",
        popupDescription: "Ez a projekt kártyák megjelínítésének a mintája.",
        listItem1: "<li>HTML</li>",
        listItem2: "<li>CSS</li>",
        listItem3: "<li>JavaScript</li>",
        listItem4: "<li>React</li>",
        listItem5: "",
        listItem6: "",
        imageSrc: "../assets/img/projects_img/Project.jpg",
        imageAlt: "Bőrdíszműves projekt kép",
        githubLink:"https://github.com/",
        githubPagesLink: "https://github.com/",
    },
    {
        id: 4,
        type: "app",
        title: "Példa projekt 4",
        technolgies: "HTML-CSS-JavaScript",
        cardDescription: "Ez a projekt kártyák megjelínítésének a mintája.",
        popupDescription: "Ez a projekt kártyák megjelínítésének a mintája.",
        listItem1: "<li>HTML</li>",
        listItem2: "<li>CSS</li>",
        listItem3: "<li>JavaScript</li>",
        listItem4: "<li>React</li>",
        listItem5: "",
        listItem6: "",
        imageSrc: "../assets/img/projects_img/Project.jpg",
        imageAlt: "Bőrdíszműves projekt kép",
        githubLink:"https://github.com/",
        githubPagesLink: "https://github.com/",
    },
    {
        id: 5,
        type: "app",
        title: "Példa projekt 5",
        technolgies: "HTML-CSS-JavaScript",
        cardDescription: "Ez a projekt kártyák megjelínítésének a mintája.",
        popupDescription: "Ez a projekt kártyák megjelínítésének a mintája.",
        listItem1: "<li>HTML</li>",
        listItem2: "<li>CSS</li>",
        listItem3: "<li>JavaScript</li>",
        listItem4: "<li>React</li>",
        listItem5: "",
        listItem6: "",
        imageSrc: "../assets/img/projects_img/Project.jpg",
        imageAlt: "Bőrdíszműves projekt kép",
        githubLink:"https://github.com/",
        githubPagesLink: "https://github.com/",
    },
    {
        id: 6,
        type: "app",
        title: "Példa projekt 6",
        technolgies: "HTML-CSS-JavaScript",
        cardDescription: "Ez a projekt kártyák megjelínítésének a mintája.",
        popupDescription: "Ez a projekt kártyák megjelínítésének a mintája.",
        listItem1: "<li>HTML</li>",
        listItem2: "<li>CSS</li>",
        listItem3: "<li>JavaScript</li>",
        listItem4: "<li>React</li>",
        listItem5: "",
        listItem6: "",
        imageSrc: "../assets/img/projects_img/Project.jpg",
        imageAlt: "Bőrdíszműves projekt kép",
        githubLink:"https://github.com/",
        githubPagesLink: "https://github.com/",
    },
    {
        id: 7,
        type: "app",
        title: "Példa projekt 7",
        technolgies: "HTML-CSS-JavaScript",
        cardDescription: "Ez a projekt kártyák megjelínítésének a mintája.",
        popupDescription: "Ez a projekt kártyák megjelínítésének a mintája.",
        listItem1: "<li>HTML</li>",
        listItem2: "<li>CSS</li>",
        listItem3: "<li>JavaScript</li>",
        listItem4: "<li>React</li>",
        listItem5: "",
        listItem6: "",
        imageSrc: "../assets/img/projects_img/Project.jpg",
        imageAlt: "Bőrdíszműves projekt kép",
        githubLink:"https://github.com/",
        githubPagesLink: "https://github.com/",
    },
    {
        id: 8,
        type: "app",
        title: "Példa projekt 8",
        technolgies: "HTML-CSS-JavaScript",
        cardDescription: "Ez a projekt kártyák megjelínítésének a mintája.",
        popupDescription: "Ez a projekt kártyák megjelínítésének a mintája.",
        listItem1: "<li>HTML</li>",
        listItem2: "<li>CSS</li>",
        listItem3: "<li>JavaScript</li>",
        listItem4: "<li>React</li>",
        listItem5: "",
        listItem6: "",
        imageSrc: "../assets/img/projects_img/Project.jpg",
        imageAlt: "Bőrdíszműves projekt kép",
        githubLink:"https://github.com/",
        githubPagesLink: "https://github.com/",
    },
    {
        id: 9,
        type: "app",
        title: "Példa projekt 9",
        technolgies: "HTML-CSS-JavaScript",
        cardDescription: "Ez a projekt kártyák megjelínítésének a mintája.",
        popupDescription: "Ez a projekt kártyák megjelínítésének a mintája.",
        listItem1: "<li>HTML</li>",
        listItem2: "<li>CSS</li>",
        listItem3: "<li>JavaScript</li>",
        listItem4: "<li>React</li>",
        listItem5: "",
        listItem6: "",
        imageSrc: "../assets/img/projects_img/Project.jpg",
        imageAlt: "Bőrdíszműves projekt kép",
        githubLink:"https://github.com/",
        githubPagesLink: "https://github.com/",
    },
    {
        id: 10,
        type: "app",
        title: "Példa projekt 10",
        technolgies: "HTML-CSS-JavaScript",
        cardDescription: "Ez a projekt kártyák megjelínítésének a mintája.",
        popupDescription: "Ez a projekt kártyák megjelínítésének a mintája.",
        listItem1: "<li>HTML</li>",
        listItem2: "<li>CSS</li>",
        listItem3: "<li>JavaScript</li>",
        listItem4: "<li>React</li>",
        listItem5: "",
        listItem6: "",
        imageSrc: "../assets/img/projects_img/Project.jpg",
        imageAlt: "Bőrdíszműves projekt kép",
        githubLink:"https://github.com/",
        githubPagesLink: "https://github.com/",
    },
   
];

export default projects;