const projects = [
    {
        id: 1,
        type: "Weboldal",
        title: "Bőrdíszműves weboldal",
        technolgies: "HTML - CSS - JavaScript",
        cardDescription: "Minta Béla bőrdíszműves portfólió weboldala.",
        popupDescription: "Minta Béla bőrdíszműves portfólió weboldala.Minta Béla bőrdíszműves portfólió weboldala.Minta Béla bőrdíszműves portfólió weboldala.Minta Béla bőrdíszműves portfólió weboldala.Minta Béla bőrdíszműves portfólió weboldala.Minta Béla bőrdíszműves portfólió weboldala.Minta Béla bőrdíszműves portfólió weboldala.Minta Béla bőrdíszműves portfólió weboldala.Minta Béla bőrdíszműves portfólió weboldala.",
        listItem1: "<li>HTML</li>",
        listItem2: "<li>CSS</li>",
        listItem3: "<li>JavaScript</li>",
        listItem4: "",
        listItem5: "",
        listItem6: "",
        imageSrc: "./assets/img/projects_img/leadherShop.webp",
        imageAlt: "Bőrdíszműves projekt kép",
        githubLink: "https://github.com/Thomas-Horvath/Leather_Portfolio-site",
        githubPagesLink: "https://thomas-horvath.github.io/Leather_Portfolio-site/",
    },
    {
        id: 2,
        type: "Weboldal",
        title: "Gipsz Jakab portfólió oldala",
        technolgies: "HTML-CSS-JavaScript",
        cardDescription: "Gipsz Jakab frontend webfejlesztő portfólió weboldala",
        popupDescription: "Gipsz Jakab frontend webfejlesztő portfólió weboldala",
        listItem1: "<li>HTML</li>",
        listItem2: "<li>CSS</li>",
        listItem3: "<li>JavaScript</li>",
        listItem4: "",
        listItem5: "",
        listItem6: "",
        imageSrc: "./assets/img/projects_img/gipsz.webp",
        imageAlt: "Bőrdíszműves projekt kép",
        githubLink: "https://github.com/Thomas-Horvath/PK_project1_porfolio_html_css-",
        githubPagesLink: "https://thomas-horvath.github.io/PK_project1_porfolio_html_css-/",
    },
    {
        id: 3,
        type: "Adatbázis",
        title: "Példa projekt 3",
        technolgies: "HTML-CSS-JS-Sass-Bootstrap",
        cardDescription: "Ez a projekt kártyák megjelenítésének a mintája.",
        popupDescription: "Ez a projekt kártyák megjelenítésének a mintája.",
        listItem1: "<li>HTML</li>",
        listItem2: "<li>CSS</li>",
        listItem3: "<li>JavaScript</li>",
        listItem4: "<li>React</li>",
        listItem5: "<li>Sass</li>",
        listItem6: "<li>Bootstrap</li>",
        imageSrc: "./assets/img/projects_img/project.webp",
        imageAlt: "Bőrdíszműves projekt kép",
        githubLink: "https://github.com/",
        githubPagesLink: "https://github.com/",
    },
    {
        id: 4,
        type: "Back-end",
        title: "Példa projekt 4",
        technolgies: "HTML-CSS-JavaScript",
        cardDescription: "Ez a projekt kártyák megjelenítésének a mintája.",
        popupDescription: "Ez a projekt kártyák megjelenítésének a mintája.",
        listItem1: "<li>HTML</li>",
        listItem2: "<li>CSS</li>",
        listItem3: "<li>JavaScript</li>",
        listItem4: "<li>React</li>",
        listItem5: "",
        listItem6: "",
        imageSrc: "./assets/img/projects_img/project.webp",
        imageAlt: "Bőrdíszműves projekt kép",
        githubLink: "https://github.com/",
        githubPagesLink: "https://github.com/",
    },
    {
        id: 5,
        type: "Alkalmazás",
        title: "Példa projekt 5",
        technolgies: "HTML-CSS-JavaScript",
        cardDescription: "Ez a projekt kártyák megjelenítésének a mintája.",
        popupDescription: "Ez a projekt kártyák megjelenítésének a mintája.",
        listItem1: "<li>HTML</li>",
        listItem2: "<li>CSS</li>",
        listItem3: "<li>JavaScript</li>",
        listItem4: "<li>React</li>",
        listItem5: "",
        listItem6: "",
        imageSrc: "./assets/img/projects_img/project.webp",
        imageAlt: "Bőrdíszműves projekt kép",
        githubLink: "https://github.com/",
        githubPagesLink: "https://github.com/",
    },
    {
        id: 6,
        type: "Weboldal",
        title: "Példa projekt 6",
        technolgies: "HTML-CSS-JavaScript",
        cardDescription: "Ez a projekt kártyák megjelenítésének a mintája.",
        popupDescription: "Ez a projekt kártyák megjelenítésének a mintája.",
        listItem1: "<li>HTML</li>",
        listItem2: "<li>CSS</li>",
        listItem3: "<li>JavaScript</li>",
        listItem4: "<li>React</li>",
        listItem5: "",
        listItem6: "",
        imageSrc: "./assets/img/projects_img/project.webp",
        imageAlt: "Bőrdíszműves projekt kép",
        githubLink: "https://github.com/",
        githubPagesLink: "https://github.com/",
    },
    {
        id: 7,
        type: "Weboldal",
        title: "Példa projekt 7",
        technolgies: "HTML-CSS-JavaScript",
        cardDescription: "Ez a projekt kártyák megjelenítésének a mintája.",
        popupDescription: "Ez a projekt kártyák megjelenítésének a mintája.",
        listItem1: "<li>HTML</li>",
        listItem2: "<li>CSS</li>",
        listItem3: "<li>JavaScript</li>",
        listItem4: "<li>React</li>",
        listItem5: "",
        listItem6: "",
        imageSrc: "./assets/img/projects_img/project.webp",
        imageAlt: "Bőrdíszműves projekt kép",
        githubLink: "https://github.com/",
        githubPagesLink: "https://github.com/",
    },
    {
        id: 8,
        type: "Weboldal",
        title: "Példa projekt 8",
        technolgies: "HTML-CSS-JavaScript",
        cardDescription: "Ez a projekt kártyák megjelenítésének a mintája.",
        popupDescription: "Ez a projekt kártyák megjelenítésének a mintája.",
        listItem1: "<li>HTML</li>",
        listItem2: "<li>CSS</li>",
        listItem3: "<li>JavaScript</li>",
        listItem4: "<li>React</li>",
        listItem5: "",
        listItem6: "",
        imageSrc: "./assets/img/projects_img/project.webp",
        imageAlt: "Bőrdíszműves projekt kép",
        githubLink: "https://github.com/",
        githubPagesLink: "https://github.com/",
    },
    {
        id: 9,
        type: "Weboldal",
        title: "Példa projekt 9",
        technolgies: "HTML - CSS - JavaScript",
        cardDescription: "Ez a projekt kártyák megjelenítésének a mintája.",
        popupDescription: "Ez a projekt kártyák megjelenítésének a mintája.",
        listItem1: "<li>HTML</li>",
        listItem2: "<li>CSS</li>",
        listItem3: "<li>JavaScript</li>",
        listItem4: "<li>React</li>",
        listItem5: "",
        listItem6: "",
        imageSrc: "./assets/img/projects_img/project.webp",
        imageAlt: "Bőrdíszműves projekt kép",
        githubLink: "https://github.com/",
        githubPagesLink: "https://github.com/",
    },
   

];

export default projects;