const projectsEnglish = [
    {
        id: 1,
        type: "Website",
        title: "Leather decorator website",
        technolgies: "HTML - CSS - JavaScript",
        cardDescription: "Béla Minta's leatherwork portfolio website.",
        popupDescription: "Béla Minta's leatherwork portfolio website.",
        listItem1: "<li>HTML</li>",
        listItem2: "<li>CSS</li>",
        listItem3: "<li>JavaScript</li>",
        listItem4: "",
        listItem5: "",
        listItem6: "",
        imageSrc: "../assets/img/projects_img/leadherShop.webp",
        imageAlt: "Leather decorater project picture",
        githubLink: "https://github.com/Thomas-Horvath/Leather_Portfolio-site",
        githubPagesLink: "https://thomas-horvath.github.io/Leather_Portfolio-site/",
    },
    {
        id: 2,
        type: "Website",
        title: "Gipsz Jakab portfolio website",
        technolgies: "HTML-CSS-JavaScript",
        cardDescription: "Gipsz Jakab frontend web developer's portfolio website",
        popupDescription: "Gipsz Jakab frontend web developer's portfolio website",
        listItem1: "<li>HTML</li>",
        listItem2: "<li>CSS</li>",
        listItem3: "<li>JavaScript</li>",
        listItem4: "",
        listItem5: "",
        listItem6: "",
        imageSrc: "../assets/img/projects_img/gipsz.webp",
        imageAlt: "Gipsz Jakab's website projekt picture",
        githubLink: "https://github.com/Thomas-Horvath/PK_project1_porfolio_html_css-",
        githubPagesLink: "https://thomas-horvath.github.io/PK_project1_porfolio_html_css-/",
    },
    {
        id: 3,
        type: "Database",
        title: "Example project 3",
        technolgies: "HTML-CSS-JS-Sass-Bootstrap",
        cardDescription: "This is a sample of how to display project cards.",
        popupDescription: "This is a sample of how to display project cards.",
        listItem1: "<li>HTML</li>",
        listItem2: "<li>CSS</li>",
        listItem3: "<li>JavaScript</li>",
        listItem4: "<li>React</li>",
        listItem5: "<li>Sass</li>",
        listItem6: "<li>Bootstrap</li>",
        imageSrc: "../assets/img/projects_img/project.webp",
        imageAlt: "Bőrdíszműves projekt kép",
        githubLink: "https://github.com/",
        githubPagesLink: "https://github.com/",
    },
    {
        id: 4,
        type: "Back-end",
        title: "Example project 4",
        technolgies: "HTML-CSS-JavaScript",
        cardDescription: "This is a sample of how to display project cards.",
        popupDescription: "This is a sample of how to display project cards.",
        listItem1: "<li>HTML</li>",
        listItem2: "<li>CSS</li>",
        listItem3: "<li>JavaScript</li>",
        listItem4: "<li>React</li>",
        listItem5: "",
        listItem6: "",
        imageSrc: "../assets/img/projects_img/project.webp",
        imageAlt: "Exemple picture",
        githubLink: "https://github.com/",
        githubPagesLink: "https://github.com/",
    },
    {
        id: 5,
        type: "Application",
        title: "Example project 5",
        technolgies: "HTML-CSS-JavaScript",
        cardDescription: "This is a sample of how to display project cards.",
        popupDescription: "This is a sample of how to display project cards.",
        listItem1: "<li>HTML</li>",
        listItem2: "<li>CSS</li>",
        listItem3: "<li>JavaScript</li>",
        listItem4: "<li>React</li>",
        listItem5: "",
        listItem6: "",
        imageSrc: "../assets/img/projects_img/project.webp",
        imageAlt: "Exemple picture",
        githubLink: "https://github.com/",
        githubPagesLink: "https://github.com/",
    },
    {
        id: 6,
        type: "Website",
        title: "Example project 6",
        technolgies: "HTML-CSS-JavaScript",
        cardDescription: "This is a sample of how to display project cards.",
        popupDescription: "This is a sample of how to display project cards.",
        listItem1: "<li>HTML</li>",
        listItem2: "<li>CSS</li>",
        listItem3: "<li>JavaScript</li>",
        listItem4: "<li>React</li>",
        listItem5: "",
        listItem6: "",
        imageSrc: "../assets/img/projects_img/project.webp",
        imageAlt: "Exemple picture",
        githubLink: "https://github.com/",
        githubPagesLink: "https://github.com/",
    },
    {
        id: 7,
        type: "Website",
        title: "Example project 7",
        technolgies: "HTML-CSS-JavaScript",
        cardDescription: "This is a sample of how to display project cards.",
        popupDescription: "This is a sample of how to display project cards.",
        listItem1: "<li>HTML</li>",
        listItem2: "<li>CSS</li>",
        listItem3: "<li>JavaScript</li>",
        listItem4: "<li>React</li>",
        listItem5: "",
        listItem6: "",
        imageSrc: "../assets/img/projects_img/project.webp",
        imageAlt: "Exemple picture",
        githubLink: "https://github.com/",
        githubPagesLink: "https://github.com/",
    },
    {
        id: 8,
        type: "Website",
        title: "Example project 8",
        technolgies: "HTML-CSS-JavaScript",
        cardDescription: "This is a sample of how to display project cards.",
        popupDescription: "This is a sample of how to display project cards.",
        listItem1: "<li>HTML</li>",
        listItem2: "<li>CSS</li>",
        listItem3: "<li>JavaScript</li>",
        listItem4: "<li>React</li>",
        listItem5: "",
        listItem6: "",
        imageSrc: "../assets/img/projects_img/project.webp",
        imageAlt: "Exemple picture",
        githubLink: "https://github.com/",
        githubPagesLink: "https://github.com/",
    },
    {
        id: 9,
        type: "Website",
        title: "Example project 9",
        technolgies: "HTML - CSS - JavaScript",
        cardDescription: "This is a sample of how to display project cards.",
        popupDescription: "This is a sample of how to display project cards.",
        listItem1: "<li>HTML</li>",
        listItem2: "<li>CSS</li>",
        listItem3: "<li>JavaScript</li>",
        listItem4: "<li>React</li>",
        listItem5: "",
        listItem6: "",
        imageSrc: "../assets/img/projects_img/project.webp",
        imageAlt: "Exemple picture",
        githubLink: "https://github.com/",
        githubPagesLink: "https://github.com/",
    },
   

];

export default projectsEnglish;